/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


import {
  AppVotesCounted as AppVotesCounted
} from './pages/app-votes-counted/app-votes-counted';

declare global {
  interface HTMLAppVotesCountedElement extends AppVotesCounted, HTMLElement {
  }
  var HTMLAppVotesCountedElement: {
    prototype: HTMLAppVotesCountedElement;
    new (): HTMLAppVotesCountedElement;
  };
  interface HTMLElementTagNameMap {
    "app-votes-counted": HTMLAppVotesCountedElement;
  }
  interface ElementTagNameMap {
    "app-votes-counted": HTMLAppVotesCountedElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-votes-counted": JSXElements.AppVotesCountedAttributes;
    }
  }
  namespace JSXElements {
    export interface AppVotesCountedAttributes extends HTMLAttributes {
      match?: any;
    }
  }
}

