/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


import {
  VoterComponent as VoterComponent
} from './components/voter-component/voter-component';

declare global {
  interface HTMLVoterComponentElement extends VoterComponent, HTMLElement {
  }
  var HTMLVoterComponentElement: {
    prototype: HTMLVoterComponentElement;
    new (): HTMLVoterComponentElement;
  };
  interface HTMLElementTagNameMap {
    "voter-component": HTMLVoterComponentElement;
  }
  interface ElementTagNameMap {
    "voter-component": HTMLVoterComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "voter-component": JSXElements.VoterComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface VoterComponentAttributes extends HTMLAttributes {
      
    }
  }
}

